04/22/2025 11:24:02 PM - root - start_bot - ERROR - Telegram API ошибка: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
Traceback (most recent call last):
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/app.py", line 82, in start_bot
    bot.polling(
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 1190, in polling
    self.__skip_updates()
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 673, in __skip_updates
    self.get_updates(offset=-1)
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
04/22/2025 11:24:08 PM - root - start_bot - ERROR - Telegram API ошибка: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
Traceback (most recent call last):
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/app.py", line 82, in start_bot
    bot.polling(
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 1190, in polling
    self.__skip_updates()
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 673, in __skip_updates
    self.get_updates(offset=-1)
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
04/22/2025 11:24:14 PM - root - start_bot - ERROR - Telegram API ошибка: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
Traceback (most recent call last):
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/app.py", line 82, in start_bot
    bot.polling(
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 1190, in polling
    self.__skip_updates()
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 673, in __skip_updates
    self.get_updates(offset=-1)
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
04/22/2025 11:24:20 PM - root - start_bot - ERROR - Telegram API ошибка: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
Traceback (most recent call last):
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/app.py", line 82, in start_bot
    bot.polling(
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 1190, in polling
    self.__skip_updates()
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 673, in __skip_updates
    self.get_updates(offset=-1)
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
04/22/2025 11:24:26 PM - root - start_bot - ERROR - Telegram API ошибка: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
Traceback (most recent call last):
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/app.py", line 82, in start_bot
    bot.polling(
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 1190, in polling
    self.__skip_updates()
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 673, in __skip_updates
    self.get_updates(offset=-1)
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkostenko/Программирование/PyCharm/Bot_Money_Currency/.venv/lib/python3.12/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
